root: true
globals: {
  "process": true
}
env:
  browser: true
  es2021: true
parser: "@typescript-eslint/parser"
extends:
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "eslint:recommended"
overrides: []
parserOptions:
  ecmaVersion: 2021
  sourceType: "module"
  project: [ "./tsconfig.json" ]
plugins:
  - "react"
  - "@typescript-eslint"
rules: {
  indent: ["error", 2]
}
